### ISSUE TITLE
Installation is not complete?

### ISSUE THREAD

**Issue by cleargoal** [flyween/vue3-quill#14]
Registration in the documentation:
```// global
  import { quillEditor, Quill } from 'vue3-quill'

  import customQuillModule from 'customQuillModule'

  Quill.register('modules/customQuillModule', customQuillModule)

  app.use(quillEditor)
```
but by the installation of the package, any 'customQuillModule' was not installed.
How to get this?

**Comment by flyween** [comment]
'customQuillModule' means 'custom module name of Quill',not a package's name called 'customQuillModule'.
I'll update README for a better example.

**Comment by cleargoal** [comment]
> 'customQuillModule' means 'custom module name of Quill',not a package's name called 'customQuillModule'. I'll update README for a better example.

OK, it's a good decision!
Thanks!
When do you plan to do it?

What if I just use this import?
```
    import { quillEditor, Quill } from 'vue3-quill'  
    app.use(quillEditor)
```
Can it work?

**Comment by flyween** [comment]
```javascript
import { quillEditor  } from 'vue3-quill'
app.use(quillEditor)
```

This should work.
And the README updated.
